version: '3.3'
services:
  clickhouse-server:
    environment:
      CLICKHOUSE_USER: username
      CLICKHOUSE_PASSWORD: password
    container_name: clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    image: clickhouse/clickhouse-server